# Hong Kong GFA Concession Exploration

In [3]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from tabula.io import read_pdf
import requests
import tempfile

### Data Cleaning

In [4]:
df = pd.read_csv("../data/BDGFA_20260510_gdb_BDGFA_converted.csv", header=0) 
df.head()

   OBJECTID  ... GeometryNorthing
0         1  ...      820347.8000
1         2  ...      816469.6000
2         3  ...      811385.0081
3         4  ...      815883.7000
4         5  ...      816511.9000

[5 rows x 36 columns]

In [9]:
df.shape

(651, 22)

In [5]:
## Remove irrelevant columns and keep everything in English

for column in df.columns:
    if "_TC" in column:
        df.drop(columns={column}, inplace=True)

df.columns

Index(['OBJECTID', 'DATASET_EN', 'ADDRESS_EN', 'SEARCH01_EN', 'SEARCH02_EN',
       'NSEARCH01_EN', 'NSEARCH02_EN', 'NSEARCH03_EN', 'NSEARCH04_EN',
       'NSEARCH05_EN', 'NSEARCH06_EN', 'NSEARCH07_EN', 'NSEARCH08_EN',
       'NSEARCH09_EN', 'NSEARCH10_EN', 'NORTHING', 'EASTING', 'LATITUDE',
       'LONGITUDE', 'LASTUPDATE', 'GeometryEasting', 'GeometryNorthing'],
      dtype='str')

| Field Name | English Description |
|---|---|
| DATASET_EN | Dataset |
| ADDRESS_EN | Address |
| SEARCH01_EN | Year |
| SEARCH02_EN | District |
| NSEARCH01_EN | Permit No. |
| NSEARCH02_EN | Date of Occupation Permit |
| NSEARCH03_EN | Building Type |
| NSEARCH04_EN | Use of Building |
| NSEARCH05_EN | Summary of GFA Concessions |
| NSEARCH06_EN | Greenery Area |
| NSEARCH07_EN | Estimated Energy Performance / consumption |
| NSEARCH08_EN | BEAM Plus Assessment Result |
| NSEARCH09_EN | Residential Thermal Transfer Value |
| NSEARCH10_EN | Overall Thermal Transfer Value of Residents' Recreational Facilities |

#### Using Python to Access PDF Tables

In [6]:
## Apply onto Summary of GFA Concessions First

url = df[df['OBJECTID'] == 1]['NSEARCH05_EN'].values ## returns a list object

r = requests.get(url[0])

with tempfile.NamedTemporaryFile(suffix="pdf") as tmp:
    tmp.write(r.content)
    tmp.flush()

    dfs = read_pdf(
        tmp.name,
        pages=1,
        multiple_tables=True
    )

gfa_summary = dfs[0]

Failed to import jpype dependencies. Fallback to subprocess.
No module named 'jpype'

In [7]:
gfa_summary

   Building Name and Address 建築物名稱及地址: 15 SHEUNG YUET ROAD, KOWLOON BAY  ... Unnamed: 3
0                          BD Ref. 屋宇署檔案編號: 2 4030 17                    ...        NaN
1   Name of Authorized Person  認可人士姓名: LAI SIU KIN...                    ...        NaN
2                 Table 1: Summary of GFA Concessions                    ...        NaN
3                                     表一:總樓面面積寬免的資料摘要                    ...        NaN
4                                                 NaN                    ...        NaN
5   2GFA Concessions subject to Overall Cap 2  App...                    ...        NaN
6   Domestic Non-domestic (平方米) Domestic Non-domestic                    ...    旅館項目的寬免
7                               住用部分 非住用部分 住用部分 非住用部分                    ...      (平方米)
8                        Domestic 0 2m 2 % m % 37 5 7                    ...          3
9                                住用部分 6 8 1041.88 2.2                    ...          4
10                           0 0 1353.011 3.61403 7 9                    ...        NaN
11                        Non-domestic 37437.746 8 10                    ...        NaN
12                                         非住用部分 9 11                    ...        NaN
13                                              10 13                    ...        NaN
14                                              11 14                    ...        NaN
15                                            12 417A                    ...        NaN
16                                            13 417B                    ...        NaN
17                                              14 18                    ...        NaN
18                                              15 19                    ...        NaN
19                                              16 20                    ...        NaN
20                                    417A 21 349.048                    ...        NaN
21                                    417B 22 237.024                    ...        NaN
22                                              18 23                    ...        NaN
23                                              19 24                    ...        NaN
24                                      20 25 347.315                    ...        NaN
25                                              21 27                    ...        NaN
26                                              22 28                    ...        NaN
27                                              23 29                    ...        NaN
28                                              26 30                    ...        NaN
29                                              27 31                    ...        NaN
30                                              28 32                    ...        NaN
31                                              29 33                    ...        NaN
32                                      30 34 505.986                    ...        NaN
33                                              31 35                    ...        NaN
34                                              32 36                    ...        NaN
35                                              33 38                    ...        NaN
36                                                 34                    ...        NaN
37                                                 35                    ...        NaN
38                                                 36                    ...        NaN
39                                                 38                    ...        NaN
40                                             Total:                    ...        NaN
41                             37437.746 0 0 2481.253                    ...          0
42                                                總計:                    ...        NaN

[43 rows x 5 columns]